'use client'
import './globals.css'
import { Inter } from 'next/font/google'
import Footer from '../components/Footer'
import { ThemeProvider } from '../utils/context'
import Navbar from '../components/Navbar'
import { useContext } from 'react'
import { ThemeContext } from '../utils/context'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Benjamin Portfolio',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <ThemeProvider>
      <Main>{children}</Main>
    </ThemeProvider>
  )
}

function Main({ children }) {
  const { theme } = useContext(ThemeContext)
  return (
    <html lang="en" className={`${theme === 'dark' && 'dark'}`}>
      <body className={inter.className}>
        <div>
          <Navbar />
          <main>{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  )
}
