'use client'
import './globals.css'
import { Inter } from 'next/font/google'
import Footer from '../components/Footer'
import { ThemeProvider } from '../utils/context'
import Navbar from '../components/Navbar'
import { styled } from 'styled-components'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Benjamin Portfolio',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  const Body = styled.body`
    font-family: ${inter.family};
  `
  return (
    <html lang="en">
      <ThemeProvider>
        <body className={inter.className}>
          <div>
            <Navbar />
            <main>{children}</main>
            <Footer />
          </div>
        </body>
      </ThemeProvider>
    </html>
  )
}
